[tool.poetry]
name = "scikit-vm"
version = "0.1.0"
description = ""
authors = ["Gavin Noronha <gavinln@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.5"
watermark = "^2.3.0"
pydot3 = "^1.0.9"
seaborn = "^0.11.2"
jupyterlab = "^3.2.8"
python-language-server = {extras = ["all"], version = "^0.36.2"}
xgboost = "^1.5.1"
lightgbm = "^3.3.2"
optuna = "^2.10.0"
umap-learn = "^0.5.2"
papermill = "^2.3.3"
jupytext = "^1.13.6"
TPOT = "^0.11.7"
ipython = "^8.0.0"
scikit-learn = {version = "^1.0.2", allow-prereleases = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
skip-string-normalization = true
